### ISSUE TITLE
First Issue Opened

### ISSUE THREAD

**Issue by lNethunter** [CaoTrongThang/SimpleMinecraftDDoS#1]
Good shit my guy(don't rat it haha)

**Comment by CaoTrongThang** [comment]
> > Not an issue but this definitely a good shit haha
> 
> Nah there is an actual issue,I've tried this on an offline aternos vanilla server and it didn't work.And on the servers it did work,only one bot joined.

![image](https://user-images.githubusercontent.com/51023235/194929319-629249e7-d4d2-4204-9800-98e275905106.png)
Yeah i've searched about it a little, and i can't fix it, you can increase the delay time to fix it.

**Comment by CaoTrongThang** [comment]
> > > > Not an issue but this definitely a good shit haha
> > > 
> > > 
> > > Nah there is an actual issue,I've tried this on an offline aternos vanilla server and it didn't work.And on the servers it did work,only one bot joined.
> > 
> > 
> > ![image](https://user-images.githubusercontent.com/51023235/194929917-7f609946-3961-41b6-9946-2e9b0b1bb71d.png) Yeah i've searched about it a little, and i can't fix it, you can increase the delay time to fix it.
> 
> Just add proxies to your tool and it'll be fixed

Working on it <3
