### ISSUE TITLE
how to use 1.19.2?

### ISSUE THREAD

**Issue by f1refa11** [CaoTrongThang/SimpleMinecraftDDoS#2]

**Comment by f1refa11** [comment]
ok

**Comment by whyusernamed** [comment]
its 1.20.4 now , i hope update is released before MC  Version 2.0.0
this "tool" has been OutDated for more than 16 Months (1 Year)

**Comment by CaoTrongThang** [comment]
Well everyone, new version has just released, try it yourself, but still, the client version is only 1.21.1
