### ISSUE TITLE
Not Working With Any Version Above 1.18.2

### ISSUE THREAD

**Issue by whyusernamed** [CaoTrongThang/SimpleMinecraftDDoS#3]
Basicly the Title is Self-Explainatory 
doesnt Work with 
1.19
1.20

P.S.:
1 quick question , how did you manage to Assemble the Tool , but no Release+Upgrade ???
( that makes me think you did not write it yourself )

**Comment by CaoTrongThang** [comment]
Well everyone, new version has just released, try it yourself, but still, the client version is only 1.21.1
